import = [
  # "~/.config/alacritty/themes/themes/afterglow.toml",
  # "~/.config/alacritty/themes/themes/alabaster_dark.toml",
  # "~/.config/alacritty/themes/themes/alacritty_0_12.toml",
  # "~/.config/alacritty/themes/themes/dracula_plus.toml",
  # "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
  "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml",
  # "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml",
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.6
## Fix gap at bottom of window from font size not aligning
dynamic_padding = true

[font]
size = 13

## `fc-list`
[font.normal]
family = "JetBrainsMonoNerdFontMono"
# family = "HackNerdFont"
style = "Regular"
